{
 "title": "Family Safety",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "device", "label": "Устройства", "query": { "query": "label_values(device)" } },
   { "name": "interval", "label": "Интервал", "query": "5m, 15m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Устройства",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device) (increase(runtime_active_window_total[1d]))/60",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "График времени",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "increase(runtime_active_window_total{device=\"$device\"}[$interval]) / 60",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Учет приложений",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(increase(runtime_active_window_total{device=\"$device\"}[1d])) / 60",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}